name: Notify Monorepo

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  dispatch-monorepo:
    runs-on: ubuntu-latest

    steps:
      - name: Send Dispatch Event
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.MONOREPO_PAT }}" \
          https://api.github.com/repos/YanghuiWu/locality_dir/dispatches \
          -d '{"event_type":"update_submodule","client_payload":{"submodule":"${{ github.repository }}"}}'
